version: "3"

services:
  api:
    build:
      context: .
      target: test
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      db_uri: "mongodb://db:27017/default"
    entrypoint: [ "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "80" ]

  db:
    image: mongo:7
    restart: always
    ports:
      - "28001:27017"
